services:
  db:
    image: postgres:16
    container_name: gymtracker-db
    environment:
      POSTGRES_USER: mygymtracker
      POSTGRES_PASSWORD: gymtracker@123
      POSTGRES_DB: gymtrackerdatabase
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    
volumes:
  pgdata:
    
